const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = relative => fs.readFileSync(path.join(root, relative), "utf8");
const html = read("webapp/index.html");
const css = read("webapp/styles.css");
const app = read("webapp/app.js");
const agencies = read("webapp/pages/agencies.js");
const library = read("webapp/pages/creator-library.js");

assert.match(css, /review-table th:first-child[\s\S]*white-space: nowrap/);
assert.match(css, /review-table td:nth-child\(2\).*min-width: 220px/);
assert.match(css, /review-table td:nth-child\(2\) a[\s\S]*text-overflow: ellipsis/);
assert.match(css, /page\[data-page="mail"\][\s\S]*max-width: 100%/);
assert.match(css, /mail-message-snippet[\s\S]*overflow-wrap: anywhere/);
assert.match(css, /mail-message-snippet[\s\S]*word-break: break-word/);
assert.match(html, /class="section-card system-tools-card"[\s\S]*id="debug-mode"[\s\S]*id="system-health-run"/);
assert.doesNotMatch(html, /<div class="section-card">\s*<div class="section-title">系统调试<\/div>/);
assert.match(html, /id="system-debug-title"[^>]*>系统调试/);
assert.match(html, /id="system-health-title"[^>]*>系统健康检查/);
assert.match(css, /\.system-debug-toggle \{ white-space: nowrap; \}/);
assert.match(css, /\.system-health-section \{ border-top: 1px solid var\(--border\);/);
assert.match(html, /开始日期/);
assert.match(html, /结束日期/);
assert.match(html, /应用筛选/);
assert.match(css, /campaign-filter-grid[\s\S]*minmax\(170px/);
assert.match(app, /capturePanel\.after\(emailPanel\)/);
assert.match(html, /id="email-enrichment-card"/);
assert.match(html, /creator-library-more-filters/);
assert.match(library, /more-filters-open/);
assert.match(css, /creator-library-secondary-filter \{ display: none/);
assert.match(html, /id="agency-detail-edit"/);
assert.match(agencies, /\/api\/local\/agencies/);
assert.match(agencies, /setEditFormVisible/);
assert.match(html, /agency-related-table/);
assert.match(css, /\.agency-related-table\s*\{[\s\S]*min-width:\s*0[\s\S]*table-layout:\s*fixed/);
assert.match(css, /\.agency-related-table\s*\{[\s\S]*min-width:\s*680px/);
assert.doesNotMatch(html, /id="dashboard-settings-card"|id="dashboard-settings-modules"|id="dashboard-layout-reset"/);
assert.match(html, /id="dashboard-v2-customize"/);
assert.match(html, /id="dashboard-customization-dialog"/);
assert.match(html, /id="dashboard-customization-modules"/);
assert.match(html, /id="dashboard-customization-reset"/);
assert.match(html, /id="dashboard-customization-done"/);
assert.match(css, /\.dashboard-customization-dialog[\s\S]*width:\s*min\(580px/);
assert.match(css, /\.dashboard-customization-modules[\s\S]*overflow-y:\s*auto/);
const dashboard = read("webapp/pages/dashboard.js");
const settings = read("webapp/pages/settings.js");
assert.match(dashboard, /function openCustomizationDialog\(\)/);
assert.match(dashboard, /renderCustomizationDialog\(\)/);
assert.match(dashboard, /saveLayout\(defaultLayout\(\)\)/);
assert.match(dashboard, /id !== "today"/);
assert.doesNotMatch(dashboard, /navigate\("settings"\)/);
assert.doesNotMatch(settings, /dashboard-settings-modules|renderDashboardLayoutSettings|dashboard-layout-reset/);
assert.match(settings, /debug_mode: app\.checkedOf\("debug-mode"\)/);
assert.match(settings, /listen\("debug-mode", "change"/);
assert.match(settings, /listen\("system-health-run", "click"/);

console.log("Product UI Layout V1.2: OK");
