export const MESSAGE = Object.freeze({
  OPEN: "KOLCONNECT_NEXT_OPEN",
  ERROR: "KOLCONNECT_NEXT_ERROR",
  COLLECT: "KOLCONNECT_NEXT_COLLECT",
  IMPORT: "KOLCONNECT_NEXT_IMPORT",
  LOAD_AGENCIES: "KOLCONNECT_NEXT_LOAD_AGENCIES",
  PAGE_CHANGED: "KOLCONNECT_NEXT_PAGE_CHANGED",
  ANALYZE_CONTENT: "KOLCONNECT_NEXT_ANALYZE_CONTENT",
  CANCEL_CONTENT: "KOLCONNECT_NEXT_CANCEL_CONTENT",
  CONTENT_PROGRESS: "KOLCONNECT_NEXT_CONTENT_PROGRESS"
});
